### PR TITLE
SSCS-10919 Fix the duplication of outcome tabs

### PR DESCRIPTION
**Pull request by mcareyma**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-10919

### Change description ###
In order stop the duplication of tabs, I have reduced lines that completely matched except for the tabid to just one tab id in benefit/data/sheets/CaseTypeTab/CaseTabType-sandl-nonprod.json

I have done this for both the listing requirements tab and the outcomes tab.

As far as I can understand tab id does not restrict the visibility of the tab it is the authorization in AuthorizationCases that does this.

This does mean that testing should look at both the Outcome tab and the Listing Requrements tab.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by DGordonV1 — COMMENTED** [review]
Is there any requirement to change the "listing requirements" fields too? Or is it something that impacts on the "Outcome" tab too?

**Comment by mcareyma** [comment]
> Is there any requirement to change the "listing requirements" fields too? Or is it something that impacts on the "Outcome" tab too?

There is no requirement, but the assumption made about the tab id field is also incorrect there and if a field that you could change appeared in the list of fields the duplication would happen there as well.

**Comment by DGordonV1** [comment]
> > Is there any requirement to change the "listing requirements" fields too? Or is it something that impacts on the "Outcome" tab too?
> 
> There is no requirement, but the assumption made about the tab id field is also incorrect there and if a field that you could change appeared in the list of fields the duplication would happen there as well.

Okay, not sure what the MO is on additional fixes / scoping for this stuff when it's not specified on ticket but it's a quick win, leave it to higher ups.

Changes look good though.

**Review by DGordonV1 — APPROVED** [review]

**Review by dattipoeHMCTS — APPROVED** [review]

**Comment by mcareyma** [comment]
This can be tested locally:
From WSL run in sscs-tribunals-api ./gradlew bootWithCCD
Create some local cases using the sscs-tribunals-api e2e sya tests (under Windows in intellij).
Log in locally to the site as super-user, select a valid case and once in the case select the drop down action "Update to case data". At the very bottom of the case select Did PO attend to "yes", then click continue. Then submit. When you return to the case there is one outcome tab.

But you will need to also check with the Action "Update Listing Requirements" as that has also been affected by my changes.

**Pull request merged**
